import 'package:flutter/material.dart';
import 'package:lucide_icons/lucide_icons.dart';
import 'package:partnex/core/theme/app_colors.dart';
import 'package:partnex/core/theme/app_sizes.dart';
import 'package:partnex/core/theme/app_typography.dart';
import 'package:partnex/core/services/ui_service.dart';

class FaqPage extends StatelessWidget {
  final bool isInvestor;

  const FaqPage({super.key, this.isInvestor = false});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.slate50,
      appBar: AppBar(
        title: Text(
          'FAQ & Help',
          style: AppTypography.textTheme.bodyLarge?.copyWith(
            fontWeight: FontWeight.w600,
            fontSize: 18,
          ),
        ),
        centerTitle: false,
        titleSpacing: 0,
        backgroundColor: AppColors.neutralWhite,
        elevation: 1,
        shadowColor: AppColors.slate200,
        leading: IconButton(
          icon: const Icon(LucideIcons.chevronLeft, color: AppColors.slate900),
          onPressed: () => uiService.goBack(),
        ),
      ),
      body: SafeArea(
        child: ListView(
          padding: EdgeInsets.all(AppSpacing.md),
          children: [
            // Text(
            //   isInvestor ? 'Understanding SME Data' : 'Understanding Your Data',
            //   style: AppTypography.textTheme.headlineMedium?.copyWith(
            //     color: AppColors.slate900,
            //     fontSize: 22,
            //     fontWeight: FontWeight.bold,
            //   ),
            // ),
            // SizedBox(height: AppSpacing.sm),
            Text(
              isInvestor ? 'Learn how Partnex calculates credibility and extracts financial records for SMEs.' : 'Learn how Partnex calculates your credibility and extracts financial records securely.',
              textAlign: TextAlign.center,
              style: AppTypography.textTheme.bodyMedium?.copyWith(
                color: AppColors.slate600,
              ),
            ),
            SizedBox(height: AppSpacing.xxl),

            _buildFaqAccordion(
              title: isInvestor ? "How is the Credibility Score calculated?" : "How is my Credibility Score calculated?",
              content: isInvestor 
                ? "The Credibility Score (0-100) is generated by our AI models analyzing multiple data points from an SME's profile and financial history. We look at their revenue consistency, expense management, time in business, and debt obligations. A higher score indicates stronger financial health and higher operational stability, signaling a more reliable investment opportunity."
                : "Your Credibility Score (0-100) is generated by our AI models analyzing multiple data points from your profile and financial history. We look at your revenue consistency, expense management, time in business, and debt obligations. A higher score indicates stronger financial health and higher operational stability, making you a more attractive prospect for investors.",
            ),

            _buildFaqAccordion(
              title: isInvestor ? "What does the Impact Score measure?" : "What does the Impact Score mean?",
              content: isInvestor
                ? "The Impact Score measures a business's potential for sustainable growth and positive economic footprint. It takes into account their industry sector, number of employees, and operational efficiency. It highlights how effectively the business scales relative to the resources it consumes."
                : "The Impact Score measures your business's potential for sustainable growth and positive economic footprint. It takes into account your industry sector, number of employees, and operational efficiency. It highlights to institutional investors how effectively your business scales relative to the resources it consumes.",
            ),

            _buildFaqAccordion(
              title: isInvestor ? "What do the Financial Metrics indicate?" : "What do the Financial Metrics mean?",
              content: isInvestor
                ? "We track three core metrics for each SME: \n\n• Revenue Trend: Shows their Year-over-Year (YoY) growth percentage.\n• Expense Ratio: The percentage of their revenue consumed by operational costs.\n• Profit Margin: The percentage of revenue that remains as profit after expenses.\n\nThese metrics provide a fast, objective snapshot of the SME's financial runway."
                : "We track three core metrics: \n\n• Revenue Trend: Shows your Year-over-Year (YoY) growth percentage.\n• Expense Ratio: The percentage of your revenue consumed by operational costs.\n• Profit Margin: The percentage of revenue that remains as profit after expenses.\n\nThese metrics provide investors with a fast snapshot of your financial runway.",
            ),

            _buildFaqAccordion(
              title: isInvestor ? "How are financial records extracted?" : "How are my financial records extracted?",
              content: isInvestor
                ? "When an SME uploads a bank statement or financial CSV, our secure extraction engine reads the transactions locally on their device. We use machine learning to categorize inflows as Revenue and outflows as Expenses or Liabilities. The SME has the opportunity to review and verify these figures before they are finalized."
                : "When you upload a bank statement or financial CSV, our secure extraction engine reads the transactions locally on your device. We use machine learning to categorize inflows as Revenue and outflows as Expenses or Liabilities. You always have the opportunity to review and edit these extracted figures before any data is sent to our servers.",
            ),

            _buildFaqAccordion(
              title: isInvestor ? "How do we calculate Loans and Liabilities?" : "How do you calculate Loans and Liabilities?",
              content: isInvestor
                ? "During extraction, the algorithm scans for recurring fixed payments or keywords indicating loan servicing (e.g., 'interest,' 'repayment,' 'credit facility'). These payments are aggregated to estimate the SME's monthly debt burden. The total outstanding liabilities are then calculated to factor into the final credibility and risk assessment."
                : "During extraction, the algorithm scans for recurring fixed payments or keywords indicating loan servicing (e.g., 'interest,' 'repayment,' 'credit facility'). These payments are aggregated to estimate your monthly debt burden. The total outstanding liabilities are then calculated to factor into your final credibility and risk assessment.",
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildFaqAccordion({
    required String title,
    required String content,
  }) {
    return Container(
      margin: EdgeInsets.only(bottom: AppSpacing.md),
      decoration: BoxDecoration(
        color: AppColors.neutralWhite,
        borderRadius: BorderRadius.circular(AppRadius.md),
        border: Border.all(color: AppColors.slate200),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.02),
            blurRadius: 4,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Theme(
        data: ThemeData(dividerColor: Colors.transparent),
        child: ExpansionTile(
          iconColor: AppColors.slate900,
          collapsedIconColor: AppColors.slate400,
          childrenPadding: EdgeInsets.only(
            left: AppSpacing.md,
            right: AppSpacing.md,
            bottom: AppSpacing.xl,
          ),
          title: Text(
            title,
            style: AppTypography.textTheme.bodyMedium?.copyWith(
              fontWeight: FontWeight.w600,
              color: AppColors.slate900,
            ),
          ),
          children: [
            Text(
              content,
              style: AppTypography.textTheme.bodyMedium?.copyWith(
                color: AppColors.slate600,
                height: 1.5,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
